// Code generated by gotemplate. DO NOT EDIT.

package types

import (
	"encoding/json"
	"fmt"
	"time"
)

var (
	_Bool = time.Time{}
)

// template type Optional(T)

// Optional wraps a value that may or may not be nil.
// If a value is present, it may be unwrapped to expose the underlying value.
type Bool optionalBool

type optionalBool struct {
	V   bool
	Set bool
}

// Of wraps the value in an optional.
func OfBool(value bool) Bool {
	return Bool{V: value, Set: true}
}

func OfBoolPtr(ptr *bool) Bool {
	if ptr == nil {
		return EmptyBool()
	} else {
		return OfBool(*ptr)
	}
}

// Empty returns an empty optional.
func EmptyBool() Bool {
	return Bool{}
}

// Get returns the value wrapped by this optional, and an ok signal for whether a value was wrapped.
func (o Bool) Get() (value bool, ok bool) {
	o.If(func(v bool) {
		value = v
		ok = true
	})
	return
}

func (o Bool) Value() (value interface{}, ok bool) {
	o.If(func(v bool) {
		value = v
		ok = true
	})
	return
}

func (o Bool) Ptr() (value *bool) {
	if o.Set {
		return &o.V
	}
	return nil
}

// IsPresent returns true if there is a value wrapped by this optional.
func (o Bool) IsPresent() bool {
	return o.Set
}

// If calls the function if there is a value wrapped by this optional.
func (o Bool) If(f func(value bool)) {
	if o.IsPresent() {
		f(o.V)
	}
}

func (o Bool) ElseFunc(f func() bool) (value bool) {
	if o.IsPresent() {
		o.If(func(v bool) { value = v })
		return
	} else {
		return f()
	}
}

// Else returns the value wrapped by this optional, or the value passed in if
// there is no value wrapped by this optional.
func (o Bool) Else(elseValue bool) (value bool) {
	return o.ElseFunc(func() bool { return elseValue })
}

// ElseZero returns the value wrapped by this optional, or the zero value of
// the type wrapped if there is no value wrapped by this optional.
func (o Bool) ElseZero() (value bool) {
	var zero bool
	return o.Else(zero)
}

// String returns the string representation of the wrapped value, or the string
// representation of the zero value of the type wrapped if there is no value
// wrapped by this optional.
func (o Bool) String() string {
	return fmt.Sprintf("%+v", o.ElseZero())
}

// MarshalJSON marshals the value being wrapped to JSON. If there is no vale
// being wrapped, the zero value of its type is marshaled.
func (o Bool) MarshalJSON() (data []byte, err error) {
	if o.Set {
		return json.Marshal(o.V)
	}
	return []byte("null"), nil
}

// UnmarshalJSON unmarshals the JSON into a value wrapped by this optional.
func (o *Bool) UnmarshalJSON(data []byte) error {
	o.Set = true
	if string(data) == "null" {
		return nil
	}
	var v bool
	err := json.Unmarshal(data, &v)
	if err != nil {
		return err
	}
	*o = OfBool(v)
	return nil
}
