// Code generated by gotemplate. DO NOT EDIT.

package types

import (
	"encoding/json"
	"fmt"
	"time"
)

var (
	_Byte = time.Time{}
)

// template type Optional(T)

// Optional wraps a value that may or may not be nil.
// If a value is present, it may be unwrapped to expose the underlying value.
type Byte optionalByte

type optionalByte struct {
	V   byte
	Set bool
}

// Of wraps the value in an optional.
func OfByte(value byte) Byte {
	return Byte{V: value, Set: true}
}

func OfBytePtr(ptr *byte) Byte {
	if ptr == nil {
		return EmptyByte()
	} else {
		return OfByte(*ptr)
	}
}

// Empty returns an empty optional.
func EmptyByte() Byte {
	return Byte{}
}

// Get returns the value wrapped by this optional, and an ok signal for whether a value was wrapped.
func (o Byte) Get() (value byte, ok bool) {
	o.If(func(v byte) {
		value = v
		ok = true
	})
	return
}

func (o Byte) Value() (value interface{}, ok bool) {
	o.If(func(v byte) {
		value = v
		ok = true
	})
	return
}

func (o Byte) Ptr() (value *byte) {
	if o.Set {
		return &o.V
	}
	return nil
}

// IsPresent returns true if there is a value wrapped by this optional.
func (o Byte) IsPresent() bool {
	return o.Set
}

// If calls the function if there is a value wrapped by this optional.
func (o Byte) If(f func(value byte)) {
	if o.IsPresent() {
		f(o.V)
	}
}

func (o Byte) ElseFunc(f func() byte) (value byte) {
	if o.IsPresent() {
		o.If(func(v byte) { value = v })
		return
	} else {
		return f()
	}
}

// Else returns the value wrapped by this optional, or the value passed in if
// there is no value wrapped by this optional.
func (o Byte) Else(elseValue byte) (value byte) {
	return o.ElseFunc(func() byte { return elseValue })
}

// ElseZero returns the value wrapped by this optional, or the zero value of
// the type wrapped if there is no value wrapped by this optional.
func (o Byte) ElseZero() (value byte) {
	var zero byte
	return o.Else(zero)
}

// String returns the string representation of the wrapped value, or the string
// representation of the zero value of the type wrapped if there is no value
// wrapped by this optional.
func (o Byte) String() string {
	return fmt.Sprintf("%+v", o.ElseZero())
}

// MarshalJSON marshals the value being wrapped to JSON. If there is no vale
// being wrapped, the zero value of its type is marshaled.
func (o Byte) MarshalJSON() (data []byte, err error) {
	if o.Set {
		return json.Marshal(o.V)
	}
	return []byte("null"), nil
}

// UnmarshalJSON unmarshals the JSON into a value wrapped by this optional.
func (o *Byte) UnmarshalJSON(data []byte) error {
	o.Set = true
	if string(data) == "null" {
		return nil
	}
	var v byte
	err := json.Unmarshal(data, &v)
	if err != nil {
		return err
	}
	*o = OfByte(v)
	return nil
}
