// Code generated by gotemplate. DO NOT EDIT.

package types

import (
	"encoding/json"
	"fmt"
	"time"
)

var (
	_Int64 = time.Time{}
)

// template type Optional(T)

// Optional wraps a value that may or may not be nil.
// If a value is present, it may be unwrapped to expose the underlying value.
type Int64 optionalInt64

type optionalInt64 struct {
	V   int64
	Set bool
}

// Of wraps the value in an optional.
func OfInt64(value int64) Int64 {
	return Int64{V: value, Set: true}
}

func OfInt64Ptr(ptr *int64) Int64 {
	if ptr == nil {
		return EmptyInt64()
	} else {
		return OfInt64(*ptr)
	}
}

// Empty returns an empty optional.
func EmptyInt64() Int64 {
	return Int64{}
}

// Get returns the value wrapped by this optional, and an ok signal for whether a value was wrapped.
func (o Int64) Get() (value int64, ok bool) {
	o.If(func(v int64) {
		value = v
		ok = true
	})
	return
}

func (o Int64) Value() (value interface{}, ok bool) {
	o.If(func(v int64) {
		value = v
		ok = true
	})
	return
}

func (o Int64) Ptr() (value *int64) {
	if o.Set {
		return &o.V
	}
	return nil
}

// IsPresent returns true if there is a value wrapped by this optional.
func (o Int64) IsPresent() bool {
	return o.Set
}

// If calls the function if there is a value wrapped by this optional.
func (o Int64) If(f func(value int64)) {
	if o.IsPresent() {
		f(o.V)
	}
}

func (o Int64) ElseFunc(f func() int64) (value int64) {
	if o.IsPresent() {
		o.If(func(v int64) { value = v })
		return
	} else {
		return f()
	}
}

// Else returns the value wrapped by this optional, or the value passed in if
// there is no value wrapped by this optional.
func (o Int64) Else(elseValue int64) (value int64) {
	return o.ElseFunc(func() int64 { return elseValue })
}

// ElseZero returns the value wrapped by this optional, or the zero value of
// the type wrapped if there is no value wrapped by this optional.
func (o Int64) ElseZero() (value int64) {
	var zero int64
	return o.Else(zero)
}

// String returns the string representation of the wrapped value, or the string
// representation of the zero value of the type wrapped if there is no value
// wrapped by this optional.
func (o Int64) String() string {
	return fmt.Sprintf("%+v", o.ElseZero())
}

// MarshalJSON marshals the value being wrapped to JSON. If there is no vale
// being wrapped, the zero value of its type is marshaled.
func (o Int64) MarshalJSON() (data []byte, err error) {
	if o.Set {
		return json.Marshal(o.V)
	}
	return []byte("null"), nil
}

// UnmarshalJSON unmarshals the JSON into a value wrapped by this optional.
func (o *Int64) UnmarshalJSON(data []byte) error {
	o.Set = true
	if string(data) == "null" {
		return nil
	}
	var v int64
	err := json.Unmarshal(data, &v)
	if err != nil {
		return err
	}
	*o = OfInt64(v)
	return nil
}
