// Code generated by gotemplate. DO NOT EDIT.

package types

import (
	"encoding/json"
	"fmt"
	"time"
)

var (
	_Int = time.Time{}
)

// template type Optional(T)

// Optional wraps a value that may or may not be nil.
// If a value is present, it may be unwrapped to expose the underlying value.
type Int optionalInt

type optionalInt struct {
	V   int
	Set bool
}

// Of wraps the value in an optional.
func OfInt(value int) Int {
	return Int{V: value, Set: true}
}

func OfIntPtr(ptr *int) Int {
	if ptr == nil {
		return EmptyInt()
	} else {
		return OfInt(*ptr)
	}
}

// Empty returns an empty optional.
func EmptyInt() Int {
	return Int{}
}

// Get returns the value wrapped by this optional, and an ok signal for whether a value was wrapped.
func (o Int) Get() (value int, ok bool) {
	o.If(func(v int) {
		value = v
		ok = true
	})
	return
}

func (o Int) Value() (value interface{}, ok bool) {
	o.If(func(v int) {
		value = v
		ok = true
	})
	return
}

func (o Int) Ptr() (value *int) {
	if o.Set {
		return &o.V
	}
	return nil
}

// IsPresent returns true if there is a value wrapped by this optional.
func (o Int) IsPresent() bool {
	return o.Set
}

// If calls the function if there is a value wrapped by this optional.
func (o Int) If(f func(value int)) {
	if o.IsPresent() {
		f(o.V)
	}
}

func (o Int) ElseFunc(f func() int) (value int) {
	if o.IsPresent() {
		o.If(func(v int) { value = v })
		return
	} else {
		return f()
	}
}

// Else returns the value wrapped by this optional, or the value passed in if
// there is no value wrapped by this optional.
func (o Int) Else(elseValue int) (value int) {
	return o.ElseFunc(func() int { return elseValue })
}

// ElseZero returns the value wrapped by this optional, or the zero value of
// the type wrapped if there is no value wrapped by this optional.
func (o Int) ElseZero() (value int) {
	var zero int
	return o.Else(zero)
}

// String returns the string representation of the wrapped value, or the string
// representation of the zero value of the type wrapped if there is no value
// wrapped by this optional.
func (o Int) String() string {
	return fmt.Sprintf("%+v", o.ElseZero())
}

// MarshalJSON marshals the value being wrapped to JSON. If there is no vale
// being wrapped, the zero value of its type is marshaled.
func (o Int) MarshalJSON() (data []byte, err error) {
	if o.Set {
		return json.Marshal(o.V)
	}
	return []byte("null"), nil
}

// UnmarshalJSON unmarshals the JSON into a value wrapped by this optional.
func (o *Int) UnmarshalJSON(data []byte) error {
	o.Set = true
	if string(data) == "null" {
		return nil
	}
	var v int
	err := json.Unmarshal(data, &v)
	if err != nil {
		return err
	}
	*o = OfInt(v)
	return nil
}
