// Code generated by gotemplate. DO NOT EDIT.

package types

import (
	"encoding/json"
	"fmt"
	"time"
)

var (
	_Rune = time.Time{}
)

// template type Optional(T)

// Optional wraps a value that may or may not be nil.
// If a value is present, it may be unwrapped to expose the underlying value.
type Rune optionalRune

type optionalRune struct {
	V   rune
	Set bool
}

// Of wraps the value in an optional.
func OfRune(value rune) Rune {
	return Rune{V: value, Set: true}
}

func OfRunePtr(ptr *rune) Rune {
	if ptr == nil {
		return EmptyRune()
	} else {
		return OfRune(*ptr)
	}
}

// Empty returns an empty optional.
func EmptyRune() Rune {
	return Rune{}
}

// Get returns the value wrapped by this optional, and an ok signal for whether a value was wrapped.
func (o Rune) Get() (value rune, ok bool) {
	o.If(func(v rune) {
		value = v
		ok = true
	})
	return
}

func (o Rune) Value() (value interface{}, ok bool) {
	o.If(func(v rune) {
		value = v
		ok = true
	})
	return
}

func (o Rune) Ptr() (value *rune) {
	if o.Set {
		return &o.V
	}
	return nil
}

// IsPresent returns true if there is a value wrapped by this optional.
func (o Rune) IsPresent() bool {
	return o.Set
}

// If calls the function if there is a value wrapped by this optional.
func (o Rune) If(f func(value rune)) {
	if o.IsPresent() {
		f(o.V)
	}
}

func (o Rune) ElseFunc(f func() rune) (value rune) {
	if o.IsPresent() {
		o.If(func(v rune) { value = v })
		return
	} else {
		return f()
	}
}

// Else returns the value wrapped by this optional, or the value passed in if
// there is no value wrapped by this optional.
func (o Rune) Else(elseValue rune) (value rune) {
	return o.ElseFunc(func() rune { return elseValue })
}

// ElseZero returns the value wrapped by this optional, or the zero value of
// the type wrapped if there is no value wrapped by this optional.
func (o Rune) ElseZero() (value rune) {
	var zero rune
	return o.Else(zero)
}

// String returns the string representation of the wrapped value, or the string
// representation of the zero value of the type wrapped if there is no value
// wrapped by this optional.
func (o Rune) String() string {
	return fmt.Sprintf("%+v", o.ElseZero())
}

// MarshalJSON marshals the value being wrapped to JSON. If there is no vale
// being wrapped, the zero value of its type is marshaled.
func (o Rune) MarshalJSON() (data []byte, err error) {
	if o.Set {
		return json.Marshal(o.V)
	}
	return []byte("null"), nil
}

// UnmarshalJSON unmarshals the JSON into a value wrapped by this optional.
func (o *Rune) UnmarshalJSON(data []byte) error {
	o.Set = true
	if string(data) == "null" {
		return nil
	}
	var v rune
	err := json.Unmarshal(data, &v)
	if err != nil {
		return err
	}
	*o = OfRune(v)
	return nil
}
