// Code generated by gotemplate. DO NOT EDIT.

package types

import (
	"encoding/json"
	"fmt"
	"time"
)

var (
	_String = time.Time{}
)

// template type Optional(T)

// Optional wraps a value that may or may not be nil.
// If a value is present, it may be unwrapped to expose the underlying value.
type String optionalString

type optionalString struct {
	V   string
	Set bool
}

// Of wraps the value in an optional.
func OfString(value string) String {
	return String{V: value, Set: true}
}

func OfStringPtr(ptr *string) String {
	if ptr == nil {
		return EmptyString()
	} else {
		return OfString(*ptr)
	}
}

// Empty returns an empty optional.
func EmptyString() String {
	return String{}
}

// Get returns the value wrapped by this optional, and an ok signal for whether a value was wrapped.
func (o String) Get() (value string, ok bool) {
	o.If(func(v string) {
		value = v
		ok = true
	})
	return
}

func (o String) Value() (value interface{}, ok bool) {
	o.If(func(v string) {
		value = v
		ok = true
	})
	return
}

func (o String) Ptr() (value *string) {
	if o.Set {
		return &o.V
	}
	return nil
}

// IsPresent returns true if there is a value wrapped by this optional.
func (o String) IsPresent() bool {
	return o.Set
}

// If calls the function if there is a value wrapped by this optional.
func (o String) If(f func(value string)) {
	if o.IsPresent() {
		f(o.V)
	}
}

func (o String) ElseFunc(f func() string) (value string) {
	if o.IsPresent() {
		o.If(func(v string) { value = v })
		return
	} else {
		return f()
	}
}

// Else returns the value wrapped by this optional, or the value passed in if
// there is no value wrapped by this optional.
func (o String) Else(elseValue string) (value string) {
	return o.ElseFunc(func() string { return elseValue })
}

// ElseZero returns the value wrapped by this optional, or the zero value of
// the type wrapped if there is no value wrapped by this optional.
func (o String) ElseZero() (value string) {
	var zero string
	return o.Else(zero)
}

// String returns the string representation of the wrapped value, or the string
// representation of the zero value of the type wrapped if there is no value
// wrapped by this optional.
func (o String) String() string {
	return fmt.Sprintf("%+v", o.ElseZero())
}

// MarshalJSON marshals the value being wrapped to JSON. If there is no vale
// being wrapped, the zero value of its type is marshaled.
func (o String) MarshalJSON() (data []byte, err error) {
	if o.Set {
		return json.Marshal(o.V)
	}
	return []byte("null"), nil
}

// UnmarshalJSON unmarshals the JSON into a value wrapped by this optional.
func (o *String) UnmarshalJSON(data []byte) error {
	o.Set = true
	if string(data) == "null" {
		return nil
	}
	var v string
	err := json.Unmarshal(data, &v)
	if err != nil {
		return err
	}
	*o = OfString(v)
	return nil
}
