// Code generated by gotemplate. DO NOT EDIT.

package types

import (
	"encoding/json"
	"fmt"
	"time"
)

var (
	_Uint32 = time.Time{}
)

// template type Optional(T)

// Optional wraps a value that may or may not be nil.
// If a value is present, it may be unwrapped to expose the underlying value.
type Uint32 optionalUint32

type optionalUint32 struct {
	V   uint32
	Set bool
}

// Of wraps the value in an optional.
func OfUint32(value uint32) Uint32 {
	return Uint32{V: value, Set: true}
}

func OfUint32Ptr(ptr *uint32) Uint32 {
	if ptr == nil {
		return EmptyUint32()
	} else {
		return OfUint32(*ptr)
	}
}

// Empty returns an empty optional.
func EmptyUint32() Uint32 {
	return Uint32{}
}

// Get returns the value wrapped by this optional, and an ok signal for whether a value was wrapped.
func (o Uint32) Get() (value uint32, ok bool) {
	o.If(func(v uint32) {
		value = v
		ok = true
	})
	return
}

func (o Uint32) Value() (value interface{}, ok bool) {
	o.If(func(v uint32) {
		value = v
		ok = true
	})
	return
}

func (o Uint32) Ptr() (value *uint32) {
	if o.Set {
		return &o.V
	}
	return nil
}

// IsPresent returns true if there is a value wrapped by this optional.
func (o Uint32) IsPresent() bool {
	return o.Set
}

// If calls the function if there is a value wrapped by this optional.
func (o Uint32) If(f func(value uint32)) {
	if o.IsPresent() {
		f(o.V)
	}
}

func (o Uint32) ElseFunc(f func() uint32) (value uint32) {
	if o.IsPresent() {
		o.If(func(v uint32) { value = v })
		return
	} else {
		return f()
	}
}

// Else returns the value wrapped by this optional, or the value passed in if
// there is no value wrapped by this optional.
func (o Uint32) Else(elseValue uint32) (value uint32) {
	return o.ElseFunc(func() uint32 { return elseValue })
}

// ElseZero returns the value wrapped by this optional, or the zero value of
// the type wrapped if there is no value wrapped by this optional.
func (o Uint32) ElseZero() (value uint32) {
	var zero uint32
	return o.Else(zero)
}

// String returns the string representation of the wrapped value, or the string
// representation of the zero value of the type wrapped if there is no value
// wrapped by this optional.
func (o Uint32) String() string {
	return fmt.Sprintf("%+v", o.ElseZero())
}

// MarshalJSON marshals the value being wrapped to JSON. If there is no vale
// being wrapped, the zero value of its type is marshaled.
func (o Uint32) MarshalJSON() (data []byte, err error) {
	if o.Set {
		return json.Marshal(o.V)
	}
	return []byte("null"), nil
}

// UnmarshalJSON unmarshals the JSON into a value wrapped by this optional.
func (o *Uint32) UnmarshalJSON(data []byte) error {
	o.Set = true
	if string(data) == "null" {
		return nil
	}
	var v uint32
	err := json.Unmarshal(data, &v)
	if err != nil {
		return err
	}
	*o = OfUint32(v)
	return nil
}
